# Generated by Django 5.1.4 on 2025-01-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='study_preference',
            field=models.CharField(blank=True, choices=[('Visual', 'Visual'), ('Text', 'Text'), ('Kinematics', 'Kinematics')], default='Visual', max_length=20, null=True),
        ),
    ]
